<a href="https://colab.research.google.com/github/barsha-1o/NUMPY/blob/main/Learning_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  #np=numpy


In [ ]:
l1 = [1,2,3]
ar1 = np.array(l1)
print(l1)
print(ar1)

[1, 2, 3]
[1 2 3]


**0-D , 1-D, 2-D AND SO ON** 


In [ ]:
zeroD =np.array(3)
oneD =np.array([1,2,3])
twoD =np.array([[1,2],[2,3]])

print(zeroD)
print(oneD)
print(twoD)

3
[1 2 3]
[[1 2]
 [2 3]]


**ARRAY INDEXING**

In [ ]:
twoD=np.array([[1,2],[2,4],[4,5]])
print(twoD[0])

[1 2]


In [ ]:
print(twoD[0][1])

2


**ARRAY SLICING**


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9]])
print(arr[1][0:2])

[6, 7]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


**ARRAY COPY**


In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])#original data
x=arr.copy()             #copy of original data
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


**ARRAY VIEW**

In [ ]:
import numpy as np

arr=np.array([1,2,3,4,5])#original data
x=arr.view()             
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


**ARRAY SHAPE**


In [ ]:
array1 = np.array([[1,2,3],[2,3,4]])
print(array1)
print(array1.shape)  #no.of rows ,no.of columns

[[1 2 3]
 [2 3 4]]
(2, 3)


In [ ]:
array1 = np.array([[1,2,3],[2,3,4]])
print(array1)
print(array1.ndim)  #tells which D array it is

[[1 2 3]
 [2 3 4]]
2


**ARRAY RESHAPING**


In [ ]:
array1=np.array([1,2,3,4,5,6,7,8])
a=array1.reshape(2,4)
print(a)

[[1 2 3 4]
 [5 6 7 8]]


**ARRAY JOINING**

In [ ]:
import numpy as np

arr1=np.array([1,2,3])
arr2=np.array([3,4,5])
arr=np.concatenate((arr1,arr2)) #JOINS MATRIX
print(arr1)
print(arr2)

[1 2 3]
[3 4 5]


In [ ]:
print(arr1+arr2) #GIVES SUM OF MATRIX

[4 6 8]


**ARRAY SPLIT**

In [ ]:
array1=np.array([1,2,3,4,5,6,7,8])

newarr=np.array_split(arr,2)
print(newarr)

[array([1, 2, 3]), array([3, 4, 5])]


**ARRAY FILTERING**

In [ ]:
arr=np.array([41,42,43,44])
x=arr[[True,False,True,False]]
print(x)

[41 43]
